### ISSUE TITLE
Stage -> Deployment type mapping(s) incorrect after save

### ISSUE THREAD

**Issue by tobyreid** [microsoft/azure-pipelines-jira#11] opened 2019-07-10 19:59 UTC
**Describe the bug**

When mapping the (classic) Azure pipeline `Stage` to JIRA `Deployment type` it appears to save successfully, but after page refresh - it shows the incorrect values..

**To Reproduce**

I have 3 Stages in my pipeline, Integration, Staging and Production - when mapping these as follows and clicking save, observe the desired output:

![image](https://user-images.githubusercontent.com/5434294/60999646-95a8ee00-a353-11e9-9f1f-133eed521142.png)

The response from vsrm.dev.azure.com comes back with a json response that causes the interface to show the following (only visible after a full page refresh)

![image](https://user-images.githubusercontent.com/5434294/60999776-da348980-a353-11e9-947f-86f915dad012.png)

It appears that all desired values I entered have had their index shifted by -1 relative to their Stage.

Looking at Fidder, the properties and values for the Stage-> Deployment type mapping appear to be saved as child properties of the correct 'Stage', but the response is incorrect:

![image](https://user-images.githubusercontent.com/5434294/61000226-e836da00-a354-11e9-80fd-2d7796b5be99.png)

**Expected behavior**
To save the properties of the Stage with correct values

**Screenshots**
See above inline

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by tobyreid** [comment] 2019-07-10 20:18
I'll add that this occurs where there is a dependency between stages:

![image](https://user-images.githubusercontent.com/5434294/61001780-31d4f400-a358-11e9-8cd5-8936a1b5b9eb.png)

**Comment by EricStG** [comment] 2019-07-10 20:23
We have the same issue in our pipeline
![image](https://user-images.githubusercontent.com/6012934/61002219-186b8200-a32f-11e9-8c10-3f7a1d2d36a8.png)

**Comment by shashban** [comment] 2019-07-16 17:19
Thanks for reporting. We'll get this checked.

**Comment by shyama1208** [comment] 2019-07-17 06:46
@tobyreid  Sorry for the inconvenience. We are unable to reproduce this issue. 
Below are the steps that we tried:
1. Create an RD with 3 stages. The stages have same dependency as in the screenshot shared by you.
2. Turn on "Report deploymnet status to Jira" option and configure the deployment types for each stage.
3. Save the RD and refresh the page.

Can you please help us with the exact repro steps.

**Comment by tobyreid** [comment] 2019-07-22 09:04
Hi @shyama1208,

Sorry for the delayed response - 

With regard to repro steps - I can capture the payload that's being sent to the server via PUT - it appears to be "correct" from my inspection.  The response from the server is incorrect.  Would you like examples of that?

I have a few other build pipelines where this behaviour isn't exhibited, I cannot determine the common factor.

**Comment by shyama1208** [comment] 2019-07-23 09:53
Never mind. We got the repro and we have fixed the issue. The fix should be deployed in few weeks.
Thanks for bringing up the issue!

**Comment by tobyreid** [comment] 2019-07-25 12:51
👍 Thanks @shyama1208

**Comment by tobyreid** [comment] 2019-08-20 11:12
This appears to be working now (for me) in Azure DevOps

**Comment by EricStG** [comment] 2019-08-20 13:52
Same here

**Comment by shyama1208** [comment] 2019-09-05 06:15
Thanks for confirming!

**Comment by prativen** [comment] 2019-11-06 16:35
Thanks for reporting the issue. Closing this as this is now fixed

**Closed** 2019-11-06 16:34 UTC
